import { useCallback, useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Check, Database, Download, FolderOpen, HardDrive, KeyRound, Laptop, Link2, LoaderCircle, Moon, Plus, RefreshCw, Save, Sun, Trash2 } from 'lucide-react';
import { native, rpc, type Job, type LocalModel, type Provider, type RoleConfig, type Settings } from '../api';
import { useApp } from '../context';
import { Button, CheckField, cx, Empty, Field, IconButton, Modal, Notice, PathInput, Section } from '../ui';
import ModelSetup from './ModelSetup';
import ToolJobs from '../ToolJobs';
import WebDavSync from './WebDavSync';

const roleNames: Record<string, string> = { transcribe: '文件转写', live_asr: '实时识别', translate: '翻译', chat: '总结与问答', vision: '图表理解', embedding: '资料库索引', tts: '语音合成' };
const roleHints: Record<string, string> = { transcribe: '音视频文件的语音识别', live_asr: '实时会话流式识别', translate: '字幕与文件名翻译', chat: '内容总结与实时问答', vision: '资料库扫描页、表格与图表', embedding: '预先建立资料库索引，供实时问答检索', tts: 'API 配音与声音合成' };
const defaultUrls = { openai: 'https://api.openai.com/v1', dashscope: 'https://dashscope.aliyuncs.com/compatible-mode/v1', gemini: 'https://generativelanguage.googleapis.com/v1beta' };

export default function SettingsPage() {
  const { connected, info, settings, run, error, success, refreshSettings, track, theme, setTheme, jobs } = useApp();
  const [tab, setTab] = useState('model');
  const [advanced, setAdvanced] = useState(false);
  const [advancedTab, setAdvancedTab] = useState('providers');
  const [provider, setProvider] = useState<Provider>();
  const [removingProvider, setRemovingProvider] = useState<Provider>();
  const [roles, setRoles] = useState<Record<string, RoleConfig>>({});
  const [models, setModels] = useState<LocalModel[]>([]);
  const [runtimes, setRuntimes] = useState<Record<string, unknown>[]>([]);
  const [modelLists, setModelLists] = useState<Record<string, { id: string; name?: string }[]>>({});
  const [busy, setBusy] = useState('');
  const [testResult, setTestResult] = useState<Record<string, { ok: boolean; message: string; latency_ms?: number }>>({});
  const [library, setLibrary] = useState('');
  const [recordAudio, setRecordAudio] = useState(true);
  const [includeMedia, setIncludeMedia] = useState(true);
  const [includeModels, setIncludeModels] = useState(false);
  const [includeSecrets, setIncludeSecrets] = useState(false);
  const [backupPassword, setBackupPassword] = useState('');
  const [importPath, setImportPath] = useState('');
  const [importPassword, setImportPassword] = useState('');
  const [restoreOpen, setRestoreOpen] = useState(false);
  const [removeModel, setRemoveModel] = useState<LocalModel>();
  useEffect(() => { if (settings) { setRoles(settings.roles || {}); setLibrary(settings.preferences.library_path || ''); setRecordAudio(settings.preferences.record_audio !== false); } }, [settings]);
  const loadModels = useCallback(async () => { const result = await run(() => rpc<{ models: LocalModel[]; runtimes: Record<string, unknown>[] }>('models.list')); if (result) { setModels(result.models); setRuntimes(result.runtimes || []); } }, [run]);
  const modelJobState = jobs.filter(job => job.tool.startsWith('models.') || job.tool === 'setup.install').map(job => `${job.id}:${job.status}`).join(',');
  useEffect(() => { if (connected && tab === 'model' && advanced && advancedTab === 'models') void loadModels(); }, [connected, tab, advanced, advancedTab, modelJobState, loadModels]);
  const savePatch = async (patch: Partial<Settings>, message?: string) => { const result = await run(() => rpc<Settings>('settings.update', { settings: patch }), message); if (result) await run(refreshSettings); return result; };
  const addProvider = () => setProvider({ id: `provider-${Date.now().toString(36)}`, name: '百炼', kind: 'dashscope', base_url: defaultUrls.dashscope, api_key: '' });
  const test = async (id: string) => { setBusy(`test-${id}`); const result = await run(() => rpc<{ ok: boolean; message: string; latency_ms?: number }>('providers.test', { provider_id: id })); if (result) setTestResult(old => ({ ...old, [id]: result })); setBusy(''); };
  const saveProvider = async (withTest = false) => {
    if (!provider) return;
    setBusy('provider');
    const clean = { ...provider }; if (!clean.api_key?.trim()) delete clean.api_key; delete clean.has_key;
    const list = settings?.providers || []; const exists = list.some(item => item.id === clean.id);
    const result = await savePatch({ providers: exists ? list.map(item => item.id === clean.id ? clean : item) : [...list, clean] }, '模型服务已保存。');
    if (result) { setProvider(undefined); if (withTest) await test(clean.id); } setBusy('');
  };
  const deleteProvider = async () => { if (!removingProvider) return; setBusy('remove-provider'); const id = removingProvider.id; const result = await savePatch({ providers: (settings?.providers || []).filter(item => item.id !== id), roles: Object.fromEntries(Object.entries(settings?.roles || {}).map(([role, value]) => [role, value.provider_id === id ? { ...value, provider_id: '' } : value])) }, '模型服务已移除。'); if (result) setRemovingProvider(undefined); setBusy(''); };
  const refreshProviderModels = async (id: string) => { if (!id) return; setBusy(`models-${id}`); const result = await run(() => rpc<{ models: { id: string; name?: string }[] }>('providers.models', { provider_id: id })); if (result) { setModelLists(old => ({ ...old, [id]: result.models })); success(`已读取 ${result.models.length} 个模型。`); } setBusy(''); };
  const installModel = async (model: LocalModel) => { setBusy(model.id); const job = await run(() => rpc<Job>('models.install', { model_id: model.id })); if (job) track(job, '已开始安装，进度显示在模型管理下方。'); setBusy(''); };
  const importModel = async () => { const files = await run(() => native.files(false)); if (!files?.length) return; setBusy('import-model'); const job = await run(() => rpc<Job>('models.import', { path: files[0] })); if (job) track(job); setBusy(''); };
  const exportModel = async (model: LocalModel) => { const path = await run(() => native.save(`${model.id.replace(/[\\/]/g, '-')}.zip`, [{ name: '离线模型包', extensions: ['zip'] }])); if (!path) return; const job = await run(() => rpc<Job>('models.export', { model_id: model.id, path })); if (job) track(job); };
  const deleteModel = async () => { if (!removeModel) return; setBusy('delete-model'); const result = await run(() => rpc('models.remove', { model_id: removeModel.id }), '模型缓存已移除。'); if (result) { setRemoveModel(undefined); await loadModels(); } setBusy(''); };
  const exportBackup = async () => { const path = await run(() => native.save(`WinToolbox-${new Date().toISOString().slice(0, 10)}.wtbackup`, [{ name: '工具箱备份', extensions: ['wtbackup', 'wtbak', 'zip'] }])); if (!path) return; setBusy('export'); const job = await run(() => rpc<Job>('backups.export', { path, include_media: includeMedia, include_models: includeModels, include_secrets: includeSecrets, ...(backupPassword ? { password: backupPassword } : {}) })); if (job) { track(job, '正在导出备份，完成后可在下方打开。'); setBackupPassword(''); } setBusy(''); };
  const importBackup = async () => { setBusy('import'); const job = await run(() => rpc<Job>('backups.import', { path: importPath, ...(importPassword ? { password: importPassword } : {}) })); if (job) { track(job, '恢复任务已提交。完成后重新打开工具箱以加载恢复的配置。'); setRestoreOpen(false); setImportPassword(''); } setBusy(''); };

  return <>
    <div className="settings-tabs tab-bar">{[['model', '模型'], ['data', '数据与备份'], ['appearance', '外观']].map(([id, label]) => <button key={id} className={cx(tab === id && 'active')} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'model' && <><ModelSetup /><details className="details settings-advanced" open={advanced} onToggle={e => setAdvanced(e.currentTarget.open)}><summary>高级设置</summary><div className="tab-bar advanced-tabs">{[['providers', '其他 API 服务'], ['roles', '功能模型'], ['models', '模型管理']].map(([id, label]) => <button key={id} className={cx(advancedTab === id && 'active')} onClick={() => setAdvancedTab(id)}>{label}</button>)}</div>
    {advanced && advancedTab === 'providers' && <><Section action={<Button variant="primary" disabled={!connected} onClick={addProvider}><Plus size={16} />添加服务</Button>}>
      {settings?.providers?.length ? <div className="provider-list">{settings.providers.map(item => <article className="provider-row" key={item.id}><div className="provider-info"><h3>{item.name}</h3><p>{item.base_url}</p><span className={cx('key-status', item.has_key && 'configured')}><KeyRound size={12} />{item.has_key ? '密钥已配置' : '未配置密钥'}</span>{testResult[item.id] && <div className={cx('test-result', testResult[item.id].ok ? 'passed' : 'failed')}>{testResult[item.id].message}{testResult[item.id].latency_ms ? ` · ${testResult[item.id].latency_ms} ms` : ''}</div>}</div><div className="provider-actions"><Button busy={busy === `test-${item.id}`} onClick={() => void test(item.id)}><Link2 size={14} />测试</Button><Button onClick={() => setProvider({ ...item, api_key: '' })}>编辑</Button><IconButton label={`移除 ${item.name}`} onClick={() => setRemovingProvider(item)}><Trash2 size={15} /></IconButton></div></article>)}</div> : <Empty title="暂无 API 服务" />}
    </Section></>}
    {advanced && advancedTab === 'roles' && <Section action={<Button variant="primary" disabled={!connected || settings?.preferences.model_mode === 'local'} busy={busy === 'roles'} onClick={async () => { setBusy('roles'); await savePatch({ roles }, '功能模型已保存。'); setBusy(''); }}><Save size={16} />保存分配</Button>}><div className="role-table"><div className="role-table-head"><span>功能</span><span>模型服务</span><span>模型 ID</span></div>{Object.entries(roleNames).map(([key, name]) => { const role = roles[key] || { provider_id: '', model: '' }; return <div className="role-row" key={key}><div><strong title={roleHints[key]}>{name}</strong></div><select aria-label={`${name}服务`} disabled={settings?.preferences.model_mode === 'local'} value={role.provider_id} onChange={e => setRoles(old => ({ ...old, [key]: { ...role, provider_id: e.target.value } }))}><option value="">请选择服务</option>{role.provider_id === 'local' && <option value="local">本地预设</option>}{settings?.providers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="input-action"><input aria-label={`${name}模型 ID`} disabled={settings?.preferences.model_mode === 'local'} list={`models-${key}`} placeholder="输入模型 ID" value={role.model} onChange={e => setRoles(old => ({ ...old, [key]: { ...role, model: e.target.value } }))} /><datalist id={`models-${key}`}>{modelLists[role.provider_id]?.map(item => <option value={item.id} key={item.id}>{item.name || item.id}</option>)}</datalist><IconButton label={`刷新${name}可用模型`} disabled={!role.provider_id || role.provider_id === 'local' || busy === `models-${role.provider_id}`} onClick={() => void refreshProviderModels(role.provider_id)}>{busy === `models-${role.provider_id}` ? <LoaderCircle size={15} className="spin" /> : <RefreshCw size={15} />}</IconButton></div></div>; })}</div><Notice>语音、视觉与索引需要对应接口。连接测试成功后，仍需选择支持该能力的模型。</Notice></Section>}
    {advanced && advancedTab === 'models' && <><Section action={<div className="button-row"><Button disabled={!connected} busy={busy === 'import-model'} onClick={importModel}><ArrowDownToLine size={16} />离线导入</Button><Button disabled={!connected} onClick={() => void loadModels()}><RefreshCw size={16} />刷新</Button></div>}>
      {models.length ? <div className="model-list">{models.map(item => { const installing = jobs.some(job => ['running', 'queued'].includes(job.status) && job.params?.model_id === item.id); return <div className="model-row" key={item.id}><span className="model-logo"><HardDrive size={21} /></span><div className="model-info"><h3>{item.name}<span className={cx('tag', item.installed && 'green')}>{item.installed ? '已安装' : item.engine}</span></h3><p>{item.description}</p><small>{item.size_hint || '大小以实际下载为准'} · {item.id}</small></div><div className="model-actions">{item.installed ? <><IconButton label={`导出 ${item.name} 离线包`} onClick={() => void exportModel(item)}><ArrowUpFromLine size={17} /></IconButton><IconButton label={`移除 ${item.name}`} onClick={() => setRemoveModel(item)}><Trash2 size={16} /></IconButton></> : <Button disabled={installing} busy={busy === item.id} onClick={() => void installModel(item)}>{installing ? <LoaderCircle className="spin" size={15} /> : <Download size={15} />}{installing ? '安装中' : '安装'}</Button>}</div></div>; })}</div> : <Empty title="模型目录尚未加载">连接本地服务后，点击刷新查看可安装能力。</Empty>}
    </Section>{runtimes.length > 0 && <Section title="运行环境"><div className="runtime-list">{runtimes.map((runtime, index) => <div key={String(runtime.id || index)}><HardDrive size={18} /><strong>{String(runtime.name || runtime.id || '运行环境')}</strong><span>{runtime.installed ? '已就绪' : String(runtime.status || '按需准备')}</span>{runtime.path ? <code>{String(runtime.path)}</code> : null}</div>)}</div></Section>}</>}
    </details><ToolJobs scope="models" title="模型处理" /></>}
    {tab === 'data' && <><Section title="保存位置"><div className="data-location"><Database size={22} /><div><span>应用数据目录</span><code>{info?.data_dir || '等待本地服务连接'}</code></div><Button disabled={!info?.data_dir} onClick={() => info && void run(() => native.open(info.data_dir))}><FolderOpen size={16} />打开</Button></div><Field label="媒体库位置（可选）" hint="用于新的媒体结果；已有文件不移动。"><PathInput value={library} onChange={setLibrary} placeholder="使用应用数据目录" onError={error} /></Field><CheckField checked={recordAudio} onChange={setRecordAudio} label="实时会话默认保存录音" /><div className="section-footer"><span /><Button disabled={!connected} busy={busy === 'preferences'} onClick={async () => { setBusy('preferences'); await savePatch({ preferences: { ...settings?.preferences, library_path: library, record_audio: recordAudio } }, '保存偏好已更新。'); setBusy(''); }}><Save size={15} />保存偏好</Button></div></Section>
      <WebDavSync />
      <div className="backup-grid"><Section title="导出备份"><div className="form-stack"><CheckField checked={includeMedia} onChange={setIncludeMedia} label="包含录音与媒体结果" /><CheckField checked={includeModels} onChange={setIncludeModels} label="包含模型缓存" hint="文件可能较大，可使用模型离线包单独迁移。" /><CheckField checked={includeSecrets} onChange={setIncludeSecrets} label="包含 API 密钥" hint="包含密钥时必须设置至少 8 位的备份密码。" /><Field label={includeSecrets ? '备份密码（必填）' : '备份密码（可选）'}><input type="password" autoComplete="new-password" value={backupPassword} onChange={e => setBackupPassword(e.target.value)} placeholder="至少 8 位，妥善保存此密码" /></Field></div><Button variant="primary" busy={busy === 'export'} disabled={!connected || (includeSecrets && backupPassword.length < 8) || (!!backupPassword && backupPassword.length < 8)} onClick={exportBackup}><ArrowUpFromLine size={16} />导出备份</Button></Section><Section title="恢复备份"><div className="form-stack"><Field label="备份文件"><PathInput file value={importPath} onChange={setImportPath} placeholder="选择 .wtbackup 或备份文件" onError={error} /></Field><Field label="备份密码"><input type="password" autoComplete="off" value={importPassword} onChange={e => setImportPassword(e.target.value)} placeholder="未加密的备份可以留空" /></Field></div><Notice tone="warning">恢复会更新当前数据。请先保存正在进行的工作，完成后重新启动工具箱。</Notice><Button disabled={!connected || !importPath.trim()} onClick={() => setRestoreOpen(true)}><ArrowDownToLine size={16} />恢复备份</Button></Section></div></>}
    {tab === 'data' && <ToolJobs scope="backups" title="本地备份" />}
    {tab === 'appearance' && <><Section ><div className="theme-options">{[['light', '浅色', Sun], ['dark', '深色', Moon], ['system', '跟随系统', Laptop]].map(([id, name, Icon]) => { const Component = Icon as typeof Sun; return <button key={String(id)} className={cx(theme === id && 'selected')} onClick={() => setTheme(String(id))}><Component size={23} /><strong>{String(name)}</strong>{theme === id && <Check size={17} />}</button>; })}</div></Section></>}
    {provider && <Modal title={settings?.providers.some(item => item.id === provider.id) ? '编辑模型服务' : '添加模型服务'} onClose={() => setProvider(undefined)}><div className="modal-body"><div className="form-grid"><Field label="服务名称"><input value={provider.name} onChange={e => setProvider({ ...provider, name: e.target.value })} /></Field><Field label="接口类型"><select value={provider.kind} onChange={e => { const kind = e.target.value as Provider['kind']; setProvider({ ...provider, kind, base_url: defaultUrls[kind] }); }}><option value="dashscope">百炼 DashScope</option><option value="openai">OpenAI 兼容</option><option value="gemini">Gemini 原生</option></select></Field></div><Field label="Base URL"><input value={provider.base_url} onChange={e => setProvider({ ...provider, base_url: e.target.value })} placeholder="https://…/v1" /></Field><Field label="API Key" hint={provider.has_key ? '已有密钥。留空保留；填写新值将替换。' : '密钥保存在本机加密存储中。'}><input type="password" autoComplete="new-password" spellCheck={false} value={provider.api_key || ''} onChange={e => setProvider({ ...provider, api_key: e.target.value })} placeholder={provider.has_key ? '••••••••（已保存）' : '输入 API Key'} /></Field><Field label="测试用模型 ID（可选）"><input value={provider.model || ''} onChange={e => setProvider({ ...provider, model: e.target.value })} placeholder="例如：qwen3.8-flash" /></Field>{provider.kind === 'dashscope' && <Field label="服务地域"><select value={provider.region || 'cn'} onChange={e => setProvider({ ...provider, region: e.target.value })}><option value="cn">中国内地</option><option value="intl">国际站</option></select></Field>}<div className="modal-footer"><Button onClick={() => setProvider(undefined)}>取消</Button><div className="button-row"><Button disabled={!provider.name.trim() || !provider.base_url.trim()} busy={busy === 'provider'} onClick={() => void saveProvider(false)}>保存</Button><Button variant="primary" disabled={!provider.name.trim() || !provider.base_url.trim()} busy={busy === 'provider'} onClick={() => void saveProvider(true)}><Link2 size={15} />保存并测试</Button></div></div></div></Modal>}
    {removingProvider && <Modal title="移除模型服务" onClose={() => setRemovingProvider(undefined)}><div className="modal-body"><p>将移除“{removingProvider.name}”。使用该服务的功能需要重新选择模型服务。</p><div className="modal-footer"><Button onClick={() => setRemovingProvider(undefined)}>取消</Button><Button variant="danger" busy={busy === 'remove-provider'} onClick={deleteProvider}>移除服务</Button></div></div></Modal>}
    {removeModel && <Modal title="移除本地模型" onClose={() => setRemoveModel(undefined)}><div className="modal-body"><p>将删除“{removeModel.name}”的本地缓存，释放磁盘空间。下次使用需要重新安装。</p><div className="modal-footer"><Button onClick={() => setRemoveModel(undefined)}>取消</Button><Button variant="danger" busy={busy === 'delete-model'} onClick={deleteModel}>移除模型</Button></div></div></Modal>}
    {restoreOpen && <Modal title="恢复备份" onClose={() => setRestoreOpen(false)}><div className="modal-body"><Notice tone="warning">即将从选定备份恢复数据。当前任务和配置可能被备份内容替换。</Notice><p className="break-word">{importPath}</p><div className="modal-footer"><Button onClick={() => setRestoreOpen(false)}>取消</Button><Button variant="primary" busy={busy === 'import'} onClick={importBackup}>开始恢复</Button></div></div></Modal>}
  </>;
}
