[package]
name = "wintoolbox"
version = "0.1.22"
description = "Windows 语音与效率工具箱"
license = "MIT"
repository = "https://github.com/thdlrt/WinToolbox"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
tauri-plugin-single-instance = "2"
tauri-plugin-global-shortcut = "2"
drag = "2.1.1"
