import { strict as assert } from 'node:assert';
import { captionReducer, defaultCaptionState } from './captions.ts';
import { CaptionPager, captionPages, captionReadMs, wrapCaptionText } from './captionText.ts';
let count = 0;
const check = (value, message) => { assert.ok(value, message); count++; };
const eq = (actual, expected, message) => { assert.deepEqual(actual, expected, message); count++; };
const cue = (seq, extra = {}) => ({ id: `c${seq}`, session_id: 'session', seq, start: seq, text: `Sentence ${seq}.`, translation: `句子${seq}。`, final: true, translation_final: true, translation_state: 'ready', duration_ms: 2500, ...extra });
let revision = 1;
let state = captionReducer(defaultCaptionState, { type: 'captions.snapshot', revision, state: { ...defaultCaptionState, active: true, session_id: 'session', status: 'listening', revision } });
const dispatch = segment => { state = captionReducer(state, { type: 'captions.segment', ...segment, revision: ++revision }); };
dispatch(cue(1, { final: false, translation_final: false }));
eq(state.segments, [], 'unstable partial never enters display cues');
dispatch(cue(1));
eq(state.segments.length, 1);
dispatch(cue(1, { text: 'Changed refinal', translation: '不匹配的新译文' }));
eq(state.segments[0].text, 'Sentence 1.', 'refinal does not replace stable source');
eq(state.segments[0].translation, '句子1。', 'changed source cannot attach a mismatched translation');
dispatch(cue(1, { final: false, translation_final: false, translation: '迟到预览' }));
eq(state.segments[0].translation, '句子1。');
dispatch(cue(2, { translation: '', translation_final: false, translation_state: 'pending' }));
dispatch(cue(2));
eq(state.segments[1].translation, '句子2。');
const stable = state;
state = captionReducer(state, { type: 'captions.snapshot', revision: 0, state: defaultCaptionState });
eq(state, stable, 'stale snapshot ignored');
state = captionReducer(state, { type: 'captions.config', revision: ++revision, options: { target_language: 'ja' } });
check(state.segments.every(item => !item.translation && item.translation_state === 'pending'), 'target change clears old language');
state = captionReducer(state, { type: 'captions.status', revision: ++revision, active: false, session_id: 'session', status: 'stopped' });
eq(state.segments, [], 'stop clears display');
state = captionReducer(state, { type: 'captions.status', revision: ++revision, active: true, session_id: 'next', status: 'listening' });
dispatch(cue(3));
eq(state.segments, [], 'new session rejects old session cues');
const measure = text => Array.from(text).length;
const layout = { key: 'wide', width: 30, originalLines: 1, translationLines: 2, originalMeasure: measure, translationMeasure: measure };
const text = 'The beginning is preserved, every middle word stays visible, and the final words are included too.';
const lines = wrapCaptionText(text, 19, measure);
eq(lines.join('').replace(/\s/g, ''), text.replace(/\s/g, ''), 'wrapping retains every non-whitespace character');
check(lines.every(line => measure(line) <= 19));
check(!lines.join('').includes('…'), 'no tail/head ellipsis inserted');
const chinese = '头部内容不能丢失。中间内容也需要阅读。最后的尾部必须完整显示。';
const chineseLines = wrapCaptionText(chinese, 9, measure);
eq(chineseLines.join(''), chinese);
check(chineseLines.every(line => measure(line) <= 9));
eq(wrapCaptionText('a 🚀 b', 3, measure).join('').replace(/\s/g, ''), 'a🚀b', 'surrogate pairs retained');
eq(wrapCaptionText('text', 0, measure), []);
const longCue = cue(1, { text, translation: chinese });
const pages = captionPages(longCue, 'bilingual', { ...layout, width: 19 });
check(pages.length > 1);
check(pages.every(page => page.cueId === longCue.id && page.seq === longCue.seq));
eq(pages.map(page => page.original).join('').replace(/\s/g, ''), text.replace(/\s/g, ''));
eq([...new Set(pages.map(page => page.translation))].join('').replace(/\s/g, ''), chinese);
check(pages.every(page => page.original && page.translation), 'bilingual pages keep both sides visible even when one side is shorter');
check(pages.every(page => page.original.split('\n').length <= 1 && page.translation.split('\n').length <= 2));
check(captionReadMs({ original: 'hello', translation: '' }) >= 2000);
check(captionReadMs({ original: text.repeat(100), translation: '' }) <= 5000);
let pager = new CaptionPager();
const update = (cues, now, mode = 'bilingual', target = 'zh', active = true, selectedLayout = layout) => pager.update('session', active, mode, target, cues, selectedLayout, now);
let frame = update([cue(1, { final: false })], 0);
check(!frame.page, 'partial not displayed');
frame = update([cue(1, { translation: '', translation_final: false, translation_state: 'pending' })], 0);
check(frame.waiting && !frame.page, 'wait for translation of same cue');
frame = pager.tick(2900);
check(!frame.page, 'stable waiting interval');
frame = update([cue(1)], 2900);
eq(frame.page.original, 'Sentence 1.');
eq(frame.page.translation, '句子1。');
frame = update([cue(1, { text: 'unstable refinal', translation: '不应重写' }), cue(2)], 3000);
eq(frame.page.original, 'Sentence 1.', 'active cue immutable');
eq(frame.page.translation, '句子1。');
frame = pager.tick(8000);
eq(frame.page.cueId, 'c2');
frame = update([cue(1), cue(2)], 9000);
eq(frame.page.cueId, 'c2', 'older translation cannot move display backwards');
frame = update([cue(2)], 9200, 'original');
eq(frame.page.original, 'Sentence 2.');
eq(frame.page.translation, '', 'original mode removes translation immediately');
frame = update([cue(2)], 9300, 'translation');
eq(frame.page.original, '');
eq(frame.page.translation, '句子2。');
frame = update([cue(2, { translation: '', translation_final: false, translation_state: 'pending' })], 9400, 'bilingual', 'ja');
check(!frame.page, 'target change clears prior display');
frame = pager.tick(12400);
eq(frame.page.original, 'Sentence 2.');
eq(frame.page.translation, '');
check(frame.page.warning.includes('未就绪'));
frame = update([cue(2, { translation: '遅い翻訳' }), cue(3, { translation: '新しい翻訳' })], 12500, 'bilingual', 'ja');
eq(frame.page.translation, '', 'late translation does not rewrite playing fallback');
frame = pager.tick(15000);
eq(frame.page.cueId, 'c3');
frame = update([], 15500, 'bilingual', 'ja', false);
check(!frame.page, 'stop clears pager');
pager = new CaptionPager();
frame = update([longCue], 0, 'bilingual', 'zh', true, { ...layout, width: 19 });
const seen = [frame.page.original];
for (let n = 1; n < pages.length; n++) { frame = pager.tick(n * 6000); seen.push(frame.page.original); }
eq(seen.join('').replace(/\s/g, ''), text.replace(/\s/g, ''), 'timed pagination plays whole sentence from head to tail');
pager = new CaptionPager();
update([cue(1)], 0);
frame = update(Array.from({ length: 12 }, (_, i) => cue(i + 1)), 1000);
check(frame.skipped, 'queue overflow is visible');
eq(frame.page.cueId, 'c1', 'catch-up never truncates current cue');
frame = pager.tick(7000);
check(frame.page.seq >= 7, 'bounded queue catches up by skipping whole waiting cues');
const orphan = wrapCaptionText('These words lead to a very short ending.', 35, measure);
check(orphan.at(-1).split(' ').length > 1, 'avoid a page with a single short trailing word');
const cjkBoundary = wrapCaptionText('一二三四五六七八九，继续。', 9, measure);
check(cjkBoundary.every(line => !/^[，。]/u.test(line)), 'closing punctuation does not start the next page');
eq(cjkBoundary.join(''), '一二三四五六七八九，继续。');
pager = new CaptionPager();
update([cue(1)], 0);
frame = update([cue(1), cue(2, { text: text.repeat(3), translation: chinese.repeat(3) }), cue(3), cue(4)], 100);
check(frame.skipped, 'queue budget includes all measured pages of a long cue');
frame = pager.tick(6000);
eq(frame.page.cueId, 'c3', 'skip a complete queued long cue rather than cut its tail');
pager = new CaptionPager();
frame = update([cue(1, { translation: '', translation_state: 'ready', translation_final: true })], 0);
check(!frame.page, 'empty ready translation must not make a blank translated cue');
frame = pager.tick(3100);
eq(frame.page.original, 'Sentence 1.');
check(!!frame.page.warning, 'empty translation falls back clearly');
console.log(`Caption UI: ${count} assertions passed (stable cues, pairing, complete pagination, queue, modes and language reset).`);
