import { strict as assert } from 'node:assert';
import { acceptExpenseUpdate, changeExpenseType, emptyExpenseFilters, expenseAmountValid, expenseDirty, expenseDraft, expenseMoney, expensePeriodValid, expenseQueryParams, expenseValidation, localDate, newExpense, newExpenseInPeriod, normalizedExpenseStatus } from './expensesState.ts';

assert.equal(localDate(new Date(2026, 8, 1, 0, 5)), '2026-09-01', 'local midnight must not become the previous UTC date');
assert.equal(newExpense('2026-09', '2026-09-10').date, '2026-09-10');
assert.equal(newExpense('2026-08', '2026-09-10').date, '2026-08-01');
for (const value of ['0', '0.00', '0.1', '12.30', '999999999.99', ' 20.00 ']) assert.equal(expenseAmountValid(value), true, value);
for (const value of ['', '-1', '1e3', '1.005', '1000000000', 'NaN', '1,000', '.5', '01.00']) assert.equal(expenseAmountValid(value), false, value);
assert.equal(expenseMoney('999999999.99'), '999,999,999.99');
assert.equal(expenseMoney('0.10'), '0.10');
const base = { ...newExpense('2026-09'), title: 'Subscription', amount: '12.30' };
assert.equal(expenseDirty(base, base), false);
assert.equal(expenseDirty({ ...base, notes: 'Draft change' }, base), true);
assert.equal(expenseValidation({ ...base, amount: '0' }), '');
assert.notEqual(expenseValidation({ ...base, title: ' ' }), '');
const item = { ...base, id: 'entry-1', revision: 2, attachments: [] };
assert.deepEqual(expenseDraft(item), base, 'draft excludes attachment metadata');
assert.equal(acceptExpenseUpdate(item, { ...item, revision: 3 }), true);
assert.equal(acceptExpenseUpdate(item, { ...item, revision: 1 }), false, 'late attachment result cannot roll back an entry revision');
assert.equal(acceptExpenseUpdate({ ...item, id: 'entry-2' }, item), false, 'late attachment result cannot change another editor');
assert.equal(acceptExpenseUpdate(undefined, item), false, 'closed editor stays closed');
assert.equal(normalizedExpenseStatus('unsubmitted', 'expense'), 'waiting');
assert.equal(normalizedExpenseStatus('submitted', 'expense'), 'waiting');
assert.equal(normalizedExpenseStatus('personal', 'expense'), 'non_reimbursable');
assert.equal(normalizedExpenseStatus('reimbursed', 'income'), 'not_applicable');
const legacy = { ...base, entry_type: undefined, status: 'personal' };
assert.equal(expenseDraft(legacy).entry_type, 'expense');
assert.equal(expenseDraft(legacy).status, 'non_reimbursable');
const income = changeExpenseType(base, 'income');
assert.equal(income.status, 'not_applicable');
assert.equal(income.category, '转账收入');
assert.equal(income.amount, '12.30', 'income amount stays unsigned decimal');
assert.equal(expenseDirty(income, base), true, 'type changes must trigger unsaved protection');
assert.equal(changeExpenseType(income, 'expense').status, 'waiting');
assert.equal(changeExpenseType(base, 'income', false).category, 'AI订阅', 'existing entry category stays intact');
assert.equal(changeExpenseType({ ...base, category: '自定义类别' }, 'income').category, '自定义类别');
assert.equal(expenseValidation({ ...income, amount: '0.00' }), '转账收入金额需大于 0。');
assert.equal(expenseValidation({ ...income, amount: '0.01' }), '');
assert.equal(expenseMoney('-1234567.80'), '-1,234,567.80', 'negative balance remains exact');
const period = { start_month: '2025-12', end_month: '2026-02' };
assert.equal(expensePeriodValid(period), true, 'cross-year inclusive range is valid');
assert.equal(expensePeriodValid({ ...period, end_month: '2025-11' }), false);
assert.equal(expensePeriodValid({ ...period, start_month: '2025-13' }), false);
assert.equal(expensePeriodValid({ ...period, end_month: '' }), false);
assert.deepEqual(expenseQueryParams(period, emptyExpenseFilters()), period, 'no month alias conflicts with range');
assert.deepEqual(expenseQueryParams(period, { ...emptyExpenseFilters(), query: ' all ', category: 'all' }), { ...period, query: 'all', category: 'all' }, 'literal all searches and categories are preserved');
assert.equal(newExpenseInPeriod(period, '2026-01-12').date, '2026-01-12');
assert.equal(newExpenseInPeriod(period, '2026-09-11').date, '2025-12-01');
console.log('Expenses: 53 assertions passed; precise decimal, legacy migration, type switching and inclusive ranges.');
