import { strict as assert } from 'node:assert';
import { expenseDateValid, expenseDraft, expenseDirty, expensePeriodValid, expenseQueryParams, emptyExpenseFilters, legacyExpenseProject, newExpenseInPeriod, newExpense } from './expensesState.ts';
import { networkParams, networkValidation, newNetworkDraft, networkDraft } from './networkState.ts';
import { belongsToTool } from './toolJobsState.ts';

const period = { start_month: '2026-01', end_month: '2026-01', start_date: '2026-09-12', end_date: '2026-09-20' };
assert.equal(expensePeriodValid(period), true, 'exact dates override legacy month fields');
assert.equal(expenseDateValid('2026-02-29'), false);
assert.equal(expenseDateValid('2024-02-29'), true);
assert.equal(expenseDateValid('2026-04-31'), false);
assert.equal(expensePeriodValid({ ...period, end_date: '2026-09-11' }), false);
assert.equal(expensePeriodValid({ ...period, start_date: '' }), false);
assert.deepEqual(expenseQueryParams(period, { ...emptyExpenseFilters(), project_id: 'travel' }), { start_date: '2026-09-12', end_date: '2026-09-20', project_id: 'travel' }, 'project and date selection must reach list API with no month aliases');
assert.equal(newExpenseInPeriod(period, '2026-09-01').date, '2026-09-12', 'new entry outside range uses first selected date, not month start');
assert.equal(newExpenseInPeriod(period, '2026-09-15').date, '2026-09-15');
const old = { ...newExpense('2026-09'), project_id: undefined };
assert.equal(expenseDraft(old).project_id, legacyExpenseProject, 'legacy entries default to built-in AI project');
const entry = { ...newExpense('2026-09'), project_id: 'travel' };
assert.equal(expenseDraft(entry).project_id, 'travel');
assert.equal(expenseDirty({ ...entry, project_id: 'other' }, entry), true, 'moving entry to a project must mark editor dirty');
const valid = { ...newNetworkDraft(), target: 'https://example.com/path' };
assert.equal(networkValidation(valid), '');
assert.deepEqual(networkParams(valid), { target: 'https://example.com/path', port: null, timeout_ms: 5000, attempts: 3 });
for (const patch of [{ target: '' }, { port: '65536' }, { port: '1.5' }, { timeout_ms: '999' }, { timeout_ms: '15001' }, { attempts: '6' }, { attempts: '0' }, { target: 'https://user:password@example.com/' }, { target: 'https://example.com/?token=secret' }, { target: 'https://example.com/#secret' }]) assert.notEqual(networkValidation({ ...valid, ...patch }), '', JSON.stringify(patch));
assert.equal(networkValidation({ ...valid, target: '::1', port: '8443', attempts: '5', timeout_ms: '15000' }), '', 'IPv6 and backend limits remain supported');
assert.equal(networkDraft({ id: 'fixture', name: 'Local', target: 'localhost', port: null, timeout_ms: 1000, attempts: 1 }).port, '');
assert.equal(belongsToTool({ tool: 'expenses.export' }, 'expenses'), true);
assert.equal(belongsToTool({ tool: 'network.run' }, 'network'), true);
assert.equal(belongsToTool({ tool: 'media' }, 'network'), false);
console.log('Ledger/network: exact-date boundaries, project edits, legacy migration, safe targets and limits passed.');
