import { strict as assert } from 'node:assert';
import { localRoleModels, modelPresetPatch } from './modelRoles.ts';
const models=[{id:'whisper',name:'Whisper',engine:'faster-whisper',installed:false},{id:'qwen-asr',name:'Qwen ASR',engine:'qwen-asr',installed:true},{id:'local-qwen',name:'Qwen',engine:'ollama',ollama_model:'qwen3.5:4b',installed:true},{id:'local-embedding',name:'Embedding',engine:'ollama',ollama_model:'embeddinggemma:latest',installed:true},{id:'cosyvoice',name:'CosyVoice',engine:'cosyvoice',installed:true}];
assert.deepEqual(localRoleModels('live_asr',models).map(x=>x.id),['whisper']);
assert.deepEqual(localRoleModels('transcribe',models).map(x=>x.id),['whisper','qwen-asr']);
assert.deepEqual(localRoleModels('chat',models).map(x=>x.id),['qwen3.5:4b']);
assert.deepEqual(localRoleModels('vision',models).map(x=>x.id),['qwen3.5:4b']);
assert.deepEqual(localRoleModels('embedding',models).map(x=>x.id),['embeddinggemma:latest']);
assert.deepEqual(localRoleModels('tts',models).map(x=>x.id),['cosyvoice']);
assert(localRoleModels('transcribe',models)[0].name.includes('需安装'));
console.log('PASS: local role model IDs and capability filtering');

const preset={id:'bailian',name:'阿里云预设',kind:'dashscope',provider:{name:'百炼',kind:'dashscope',base_url:'https://default.invalid/v1',region:'cn'},models:{chat:'qwen-text',parcel:'qwen-text',parcel_vision:'qwen-vision'}};
const custom={id:'other',name:'Custom',kind:'openai',base_url:'https://other.invalid/v1',api_key:'opaque-other-key'};
const existing={id:'existing',name:'My region',kind:'dashscope',base_url:'https://custom.invalid/v1',region:'intl',api_key:'opaque-existing-key'};
const source={providers:[custom,existing],roles:{chat:{provider_id:'other',model:'old'},custom_role:{provider_id:'other',model:'preserve'}},preferences:{model_mode:'local'}};
const applied=modelPresetPatch(source,preset,'existing','unused');
assert(!('providers' in applied),'existing service settings and secret store are not rewritten');
assert(!('preferences' in applied),'global mode must not change');
assert.deepEqual(applied.roles.custom_role,source.roles.custom_role);
assert.deepEqual(applied.roles.parcel_vision,{provider_id:'existing',model:'qwen-vision'});
assert.equal(source.providers[1].api_key,'opaque-existing-key');
assert.throws(()=>modelPresetPatch(source,preset,'','new-id'),/请选择/);
assert.throws(()=>modelPresetPatch(source,preset,'other','new-id'),/已变化/);
const created=modelPresetPatch({...source,providers:[custom]},preset,'','new-id');
assert.deepEqual(created.providers[0],custom);
assert.equal(created.providers[1].id,'new-id');
assert.equal(created.providers[1].api_key,undefined);
assert.equal(created.roles.chat.provider_id,'new-id');
assert.deepEqual(created.roles.custom_role,source.roles.custom_role);
console.log('PASS: preset preserves providers, credentials, custom roles and global mode');
