import { strict as assert } from 'node:assert';
import { readFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { courseExport, PHONETICS_CHANNEL, phoneticsState, PhoneticsWriter, trustedPhoneticsMessage } from './phonetics.ts';
const base = { done: [], custom: '', checks: {}, best: 0 };
assert.deepEqual(phoneticsState(base), base);
const filled = { done: [1, 0, 4], custom: 'My **method** / works.', checks: { 'opening-0': true }, best: 6 };
assert.deepEqual(phoneticsState(filled), filled);
for (const invalid of [null, [], {}, { ...base, extra: true }, { ...base, done: [5] }, { ...base, done: [1, 1] }, { ...base, best: 7 }, { ...base, custom: 'a'.repeat(20001) }, { ...base, checks: { a: 'yes' } }, { ...base, checks: { '\n': true } }]) assert.throws(() => phoneticsState(invalid));
const source = {}, other = {}, origin = 'http://tauri.localhost', token = 'test-token';
const event = { source, origin, data: { channel: PHONETICS_CHANNEL, token, type: 'change', state: filled } };
assert.equal(trustedPhoneticsMessage(event, source, origin, token), true);
assert.equal(trustedPhoneticsMessage({ ...event, source: other }, source, origin, token), false);
assert.equal(trustedPhoneticsMessage({ ...event, origin: 'https://example.com' }, source, origin, token), false);
assert.equal(trustedPhoneticsMessage(event, source, origin, 'wrong'), false);
assert.equal(trustedPhoneticsMessage({ ...event, data: { ...event.data, type: 'delete-all' } }, source, origin, token), false);
assert.deepEqual(courseExport('练习.md', [65, 66]), { name: '练习.md', bytes: [65, 66] });
for (const [name, bytes] of [['../bad.md', [1]], ['bad.exe', [1]], ['good.md', [256]], ['good.md', [-1]], ['good.md', 'text']]) assert.throws(() => courseExport(name, bytes));
const written = []; let release;
const writer = new PhoneticsWriter(async value => { written.push(value.custom); if (written.length === 1) await new Promise(resolve => { release = resolve; }); });
const one = writer.enqueue({ ...base, custom: 'first' });
const two = writer.enqueue({ ...base, custom: 'intermediate' });
const three = writer.enqueue({ ...base, custom: 'latest' });
assert.deepEqual(written, ['first'], 'only one write in flight');
release(); await Promise.all([one, two, three]);
assert.deepEqual(written, ['first', 'latest'], 'pending edits coalesce without reordering');
let attempts = 0;
const retry = new PhoneticsWriter(async value => { attempts++; assert.equal(value.custom, 'retry me'); if (attempts === 1) throw new Error('fixture failure'); });
await assert.rejects(retry.enqueue({ ...base, custom: 'retry me' }));
await retry.flush(); assert.equal(attempts, 2, 'failed snapshot remains retryable');
const app = readFileSync('public/phonetics/app.js', 'utf8');
const html = readFileSync('public/phonetics/index.html', 'utf8');
assert.equal(/localStorage/.test(app), false, 'embedded course never reads or writes browser progress');
assert.equal(/class="hero"|<header>|<footer>/.test(html), false, 'promotional markup removed');
assert.ok(app.includes('const saved=await initialState;'), 'course waits for loaded backend state');
assert.ok(app.includes('await pending') && app.includes('stream.getTracks().forEach(track=>track.stop())'), 'shutdown waits for pending microphone permission and releases tracks');
const sourceAudio = 'E:/code/obsidian/CsNotes/docs/科研/学术英语/音标入门/audio';
const audio = readdirSync('public/phonetics/audio').filter(name => name.endsWith('.mp3'));
assert.equal(audio.length, 45);
for (const name of audio) assert.equal(createHash('sha256').update(readFileSync(`public/phonetics/audio/${name}`)).digest('hex'), createHash('sha256').update(readFileSync(`${sourceAudio}/${name}`)).digest('hex'), `audio copy differs: ${name}`);
console.log('Phonetics: state, message origin/source/token, serialized retryable writes, export validation and all 45 audio hashes passed.');
