import { strict as assert } from 'node:assert';
import { acceptPracticeCompletion, emptyPracticeDraft, filterPracticeItems, practiceDirty, practiceDraft, practicePlayable } from './practiceState.ts';

const fragment = { id: 'fragment', parent_id: 'parent', text: 'A short fragment.', voice: 'Cherry', model: 'tts', created_at: 1, status: 'ready', stale: false, sentences: [{ text: 'A short fragment.', audio_id: 'fragment-audio' }] };
const parent = { id: 'parent', text: 'A paragraph containing several sentences.', voice: 'Cherry', model: 'tts', created_at: 1, revision: 3, folder_id: null, status: 'ready', stale: false, sentences: [{ text: 'A paragraph containing several sentences.', audio_id: 'paragraph-audio' }], fragments: [fragment] };
const draft = practiceDraft(parent);
assert.equal(practiceDirty(draft, parent), false);
assert.equal(practiceDirty({ ...draft, text: draft.text + ' More.' }, parent), true);
assert.equal(practiceDirty({ ...draft, voice: 'Aiden' }, parent), true);
assert.equal(practiceDirty({ ...draft, folder_id: 'folder' }, parent), true);
assert.equal(practiceDirty({ ...draft, folder_id: '' }, parent), false);
assert.equal(practiceDirty(emptyPracticeDraft()), false);
assert.equal(practiceDirty({ ...emptyPracticeDraft(), voice: 'Aiden' }), false, 'blank unsaved paragraph does not require a discard confirmation');
assert.equal(practiceDirty({ ...emptyPracticeDraft(), text: 'New paragraph.' }), true);
assert.equal(practicePlayable(parent), true);
assert.equal(practicePlayable(fragment), true, 'fragment is independently playable without replacing its parent data');
assert.equal(practicePlayable({ ...parent, stale: true }), false, 'old audio must not masquerade as edited text');
assert.equal(practicePlayable({ ...parent, status: 'generating' }), false);
assert.equal(practicePlayable({ ...parent, status: 'draft', sentences: [] }), false);
assert.equal(practicePlayable({ ...parent, status: 'error' }), false);
assert.equal(practicePlayable({ ...parent, sentences: [{ text: 'Missing cached file id', audio_id: '' }] }), false);
const other = { ...parent, id: 'other', folder_id: 'folder' };
assert.deepEqual(filterPracticeItems([parent, other], 'all').map(item => item.id), ['parent', 'other']);
assert.deepEqual(filterPracticeItems([parent, other], 'unfiled').map(item => item.id), ['parent']);
assert.deepEqual(filterPracticeItems([parent, other], 'folder').map(item => item.id), ['other']);
assert.equal(filterPracticeItems([parent], 'all').length, 1, 'child fragments never expand the paragraph list');
assert.equal(acceptPracticeCompletion(parent.id, parent.id, false), true);
assert.equal(acceptPracticeCompletion(parent.id, other.id, false), false, 'finishing an old paragraph must not replace the newly selected one');
assert.equal(acceptPracticeCompletion(parent.id, parent.id, true), false, 'a job callback must not overwrite edited text');
assert.equal(acceptPracticeCompletion(parent.id, undefined, false), false, 'an old completion must not open over a new draft');
assert.equal(parent.id, 'parent');
assert.equal(parent.fragments[0].parent_id, parent.id);
console.log('Practice state: 25 assertions passed (dirty guards, folders, fragment ownership, playback readiness, stale completions).');
