import { strict as assert } from 'node:assert';
import { belongsToTool, processing, retryable, toolJobs } from './toolJobsState.ts';
const job = (id, tool, params = {}, status = 'completed') => ({ id, tool, params, status, created_at: id, progress: 0, message: '', artifacts: [] });
const files = job('2026-02', 'media', { paths: ['D:/video.mp4'] });
const recording = job('2026-03', 'media', { origin: 'live', paths: ['D:/audio.wav'] });
const oldRecording = job('2026-01', 'media', { paths: ['D:\\data\\sessions\\abc\\audio.wav'] });
assert(belongsToTool(files, 'media'));
assert(!belongsToTool(recording, 'media'));
assert(belongsToTool(recording, 'live'));
assert(belongsToTool(oldRecording, 'live'));
assert(!belongsToTool(oldRecording, 'media'));
assert(belongsToTool(job('x', 'knowledge-ingest', { collection_id: 'a' }), 'knowledge', 'a'));
assert(!belongsToTool(job('x', 'knowledge-ingest', { collection_id: 'b' }), 'knowledge', 'a'));
assert(!belongsToTool(job('x', 'webdav.upload'), 'backups'));
assert(!belongsToTool(job('x', 'setup.install'), 'models'));
assert(belongsToTool(job('x', 'setup.install'), 'presets'));
assert(belongsToTool(job('x', 'backup-export'), 'backups'));
assert(belongsToTool(job('x', 'plugin'), 'plugins'));
assert(processing('cancelling'));
assert(!retryable('completed'));
assert(retryable('interrupted'));
const active = job('2025-01', 'media', {}, 'running');
assert.deepEqual(toolJobs([oldRecording, files, active, recording], 'media').map(j => j.id), [active.id, files.id]);
console.log('Tool-local job routing: 16 assertions passed.');
